### PR TITLE
Support aeson-2.0

### LINKED ISSUE #120: Couldn't match expected type ‘T.Key’ with actual type ‘Text’
I’m trying to upgrade a project of mine to a newer set of dependencies, and I am encountering this build error:
```
Building library for aws-lambda-haskell-runtime-4.1.1..
[ 1 of 17] Compiling Aws.Lambda.Runtime.API.Version
[ 2 of 17] Compiling Aws.Lambda.Runtime.API.Endpoints
[ 3 of 17] Compiling Aws.Lambda.Runtime.Error
[ 4 of 17] Compiling Aws.Lambda.Runtime.Environment
[ 5 of 17] Compiling Aws.Lambda.Runtime.ApiInfo
[ 6 of 17] Compiling Aws.Lambda.Runtime.Context
[ 7 of 17] Compiling Aws.Lambda.Runtime.StandaloneLambda.Types
[ 8 of 17] Compiling Aws.Lambda.Utilities
[ 9 of 17] Compiling Aws.Lambda.Runtime.APIGateway.Types

src/Aws/Lambda/Runtime/APIGateway/Types.hs:216:31: error:
    • Couldn't match expected type ‘T.Key’ with actual type ‘Text’
    • In the first argument of ‘(.=)’, namely ‘k’
      In the expression: k .= v
      In an equation for ‘headerToPair’:
          headerToPair (cibyte, bstr)
            = k .= v
            where
                k = (T.decodeUtf8 . CI.original) cibyte
                v = T.decodeUtf8 bstr
    |
216 | headerToPair (cibyte, bstr) = k .= v
    |                               ^
```

This is building against aeson-2.0.3.0, so that’s probably the issue.

Any plans for aeson-2 compatibility?

### PR DESCRIPTION
**Pull request by nomeata**
fixes #120. 

Following the advice in https://github.com/haskell/aeson/issues/881#issuecomment-944920664. 

It compiles, did not do any more checks.

### CODE REVIEW

**Comment by nomeata** [comment]
Does this need to be backward compatible?

**Comment by maerten** [comment]
This PR fixes the issue for me 👍 
using stack ; ghc9.2.4 ; stackage nightly-2022-09-12

**Comment by NickSeagull** [comment]
Was about to merge+publish this, but between this one and #122 , which one should we use?

**Review by nomeata — COMMENTED** [review]
Hardly any difference. Maybe takes my code (including the cabal file refinement), but merge in the stack-related changes?

**Comment by nomeata** [comment]
Or is the .cabal file autogenerated in thus repo? (Haven't worked with package.yaml yet) In that case my change is a bit futile, is it?

**Comment by seanhess** [comment]
I'm jumping in to make some changes to an old project and hitting this issue. Any idea when this might be released? How can I help?

**Comment by NickSeagull** [comment]
Working on merging this, thanks for being patient with the long delays 😅

**Comment by NickSeagull** [comment]
Thanks for this, I've opened a PR with this PR's contents in order to add some CICD checks too. #124.

Closing this one in order to merge the other one

**Comment by NickSeagull** [comment]
Just so you know 1.4.2 has been published with Aeson 2.0 support

**Pull request closed without merging**
